# Generated by Django 4.0 on 2022-12-19 11:07

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Speech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story_Details',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('story_title', models.CharField(max_length=500)),
                ('story_level', models.CharField(max_length=10)),
                ('story_image', models.FileField(upload_to='./static/images')),
                ('story_para', models.FileField(upload_to='./static/books')),
            ],
        ),
        migrations.DeleteModel(
            name='Book_Details',
        ),
    ]
